In [1]:
import pandas as pd
import numpy as np

## Daily Ridership

In [7]:
df=pd.read_csv('Datasets/MTA_Daily_Ridership_Data__2020_-_2025_20250114.csv')
df.head()

,Date,Subways: Total Estimated Ridership,Subways: % of Comparable Pre-Pandemic Day,Buses: Total Estimated Ridership,Buses: % of Comparable Pre-Pandemic Day,LIRR: Total Estimated Ridership,LIRR: % of Comparable Pre-Pandemic Day,Metro-North: Total Estimated Ridership,Metro-North: % of Comparable Pre-Pandemic Day,Access-A-Ride: Total Scheduled Trips,Access-A-Ride: % of Comparable Pre-Pandemic Day,Bridges and Tunnels: Total Traffic,Bridges and Tunnels: % of Comparable Pre-Pandemic Day,Staten Island Railway: Total Estimated Ridership,Staten Island Railway: % of Comparable Pre-Pandemic Day
0,03/01/2020,2212965,0.97,984908,0.99,86790,1.00,55825,0.59,19922,1.13,786960,0.98,1636,0.52
1,03/02/2020,5329915,0.96,2209066,0.99,321569,1.03,180701,0.66,30338,1.02,874619,0.95,17140,1.07
2,03/03/2020,5481103,0.98,2228608,0.99,319727,1.02,190648,0.69,32767,1.10,882175,0.96,17453,1.09
3,03/04/2020,5498809,0.99,2177165,0.97,311662,0.99,192689,0.70,34297,1.15,905558,0.98,17136,1.07
4,03/05/2020,5496453,0.99,2244515,1.00,307597,0.98,194386,0.70,33209,1.12,929298,1.01,17203,1.08

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1776 entries, 0 to 1775
Data columns (total 15 columns):
 #   Column                                                   Non-Null Count  Dtype
---  ------                                                   --------------  -----
 0   Date                                                     1776 non-null   object
 1   Subways: Total Estimated Ridership                       1776 non-null   int64
 2   Subways: % of Comparable Pre-Pandemic Day                1776 non-null   float64
 3   Buses: Total Estimated Ridership                         1776 non-null   int64
 4   Buses: % of Comparable Pre-Pandemic Day                  1776 non-null   float64
 5   LIRR: Total Estimated Ridership                          1776 non-null   int64
 6   LIRR: % of Comparable Pre-Pandemic Day                   1776 non-null   float64
 7   Metro-North: Total Estimated Ridership                   1776 non-null   int64
 8   Metro-North: % of Comparable Pre-Pandemic Day            1776 non-null   float64
 9   Access-A-Ride: Total Scheduled Trips                     1776 non-null   int64
 10  Access-A-Ride: % of Comparable Pre-Pandemic Day          1776 non-null   float64
 11  Bridges and Tunnels: Total Traffic                       1776 non-null   int64
 12  Bridges and Tunnels: % of Comparable Pre-Pandemic Day    1776 non-null   float64
 13  Staten Island Railway: Total Estimated Ridership         1776 non-null   int64
 14  Staten Island Railway: % of Comparable Pre-Pandemic Day  1776 non-null   float64
dtypes: float64(7), int64(7), object(1)
memory usage: 208.2+ KB

In [12]:
df['Date'] = pd.to_datetime(df['Date'])
min_year= df['Date'].year.min()
max_year= df['Date'].max()
print(f'The min year on file is {min_year} and max is {max_year}')

AttributeError: 'Series' object has no attribute 'year'